# Usar la imagen oficial de Python
FROM python:3.9

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto
COPY . /app

# Instalar las dependencias
RUN pip install requests

# Ejecutar el script cuando se inicie el contenedor
CMD ["python", "app.py"]
